/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef nvr_CONSTANTS_H
#define nvr_CONSTANTS_H

#include "nvr_types.h"

namespace com { namespace nvr { namespace thrift {

class nvrConstants {
 public:
  nvrConstants();

};

extern const nvrConstants g_nvr_constants;

}}} // namespace

#endif
